// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMvRhQYO3SKIoW3iRp2erCY8bQJ2qQPU',
    appId: '1:493546047626:web:04d012f585f85f8d7f4573',
    messagingSenderId: '493546047626',
    projectId: 'dronestream-219f5',
    authDomain: 'dronestream-219f5.firebaseapp.com',
    databaseURL: 'https://dronestream-219f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dronestream-219f5.appspot.com',
    measurementId: 'G-MGK87C6KGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsB1eoRst2WUUdG7z4-B3_NWgbaiQDLwU',
    appId: '1:493546047626:android:3259332caab323857f4573',
    messagingSenderId: '493546047626',
    projectId: 'dronestream-219f5',
    databaseURL: 'https://dronestream-219f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dronestream-219f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7k9wZf3Wdty_SCqXZxYRm6enaTYMlQw',
    appId: '1:493546047626:ios:1749764b014d208e7f4573',
    messagingSenderId: '493546047626',
    projectId: 'dronestream-219f5',
    databaseURL: 'https://dronestream-219f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dronestream-219f5.appspot.com',
    iosBundleId: 'com.example.dronestreamFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7k9wZf3Wdty_SCqXZxYRm6enaTYMlQw',
    appId: '1:493546047626:ios:8370cdecb6d251a07f4573',
    messagingSenderId: '493546047626',
    projectId: 'dronestream-219f5',
    databaseURL: 'https://dronestream-219f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dronestream-219f5.appspot.com',
    iosBundleId: 'com.example.dronestreamFirebase.RunnerTests',
  );
}
